### ISSUE TITLE
Channel not producing videos

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/Freeform.bundle#3]
The SEASONS URL no longer is available, so URL returns a 404 error and causes an error in the init.py on line 65. The web page says the "/vp2/s/carousel" directory is not available.

They may have changed to using new json similar to the one used by the ABC channel.

**Comment by sander1** [comment]
I'm back home tomorrow and will take a look at this.  The ABC rewrite/update makes use of some of the feeds used by their iPad app. I think we can fix this service and channel the same way.

**Comment by shopgirl284** [comment]
Need to also update the URL service to use the new format used by ABC.

**Comment by sander1** [comment]
> Need to also update the URL service to use the new format used by ABC.

Yep, this requires a complete rewrite, hopefully we can copy/paste most of the code from the new ABC channel.

**Comment by shopgirl284** [comment]
See PR#4.
